#pragma classflags("forceupdate")
#pragma namespace ("\\\\.\\Root\\WMI")

/////////////////////////////////////////////////////////////////////////////
//
//  ADONETDIAG.ETW

[
 dynamic: ToInstance,
 Description("ADONETDIAG.ETW"),
 Guid("{7ACDCAC8-8947-F88A-E51A-24018F5129EF}"),
 locale("MS\\0x409")
]
class Bid2Etw_ADONETDIAG_ETW : EventTrace
{
};

[
 dynamic: ToInstance,
 Description("ADONETDIAG.ETW"),
 Guid("{7ACDCAC9-8947-F88A-E51A-24018F5129EF}"),
 DisplayName("AdoNetDiag"),
 locale("MS\\0x409")
]
class Bid2Etw_ADONETDIAG_ETW_Trace : Bid2Etw_ADONETDIAG_ETW
{
};

[
 dynamic: ToInstance,
 Description("ADONETDIAG.ETW formatted output (A)"),
 EventType(17),
 EventTypeName("TextA"),
 locale("MS\\0x409")
]
class Bid2Etw_ADONETDIAG_ETW_Trace_TextA : Bid2Etw_ADONETDIAG_ETW_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringA"),
     extension("RString"),
     read
    ]
    object msgStr;
};

[
 dynamic: ToInstance,
 Description("ADONETDIAG.ETW formatted output (W)"),
 EventType(18),
 EventTypeName("TextW"),
 locale("MS\\0x409")
]
class Bid2Etw_ADONETDIAG_ETW_Trace_TextW : Bid2Etw_ADONETDIAG_ETW_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringW"),
     extension("RWString"),
     read
    ]
    object msgStr;
};

/////////////////////////////////////////////////////////////////////////////
//
//  System.Data.1

[
 dynamic: ToInstance,
 Description("System.Data.1"),
 Guid("{914ABDE2-171E-C600-3348-C514171DE148}"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_1 : EventTrace
{
};

[
 dynamic: ToInstance,
 Description("System.Data.1"),
 Guid("{914ABDE3-171E-C600-3348-C514171DE148}"),
 DisplayName("System.Data"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_1_Trace : Bid2Etw_System_Data_1
{
};

[
 dynamic: ToInstance,
 Description("System.Data.1 formatted output (A)"),
 EventType(17),
 EventTypeName("TextA"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_1_Trace_TextA : Bid2Etw_System_Data_1_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringA"),
     extension("RString"),
     read
    ]
    object msgStr;
};

[
 dynamic: ToInstance,
 Description("System.Data.1 formatted output (W)"),
 EventType(18),
 EventTypeName("TextW"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_1_Trace_TextW : Bid2Etw_System_Data_1_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringW"),
     extension("RWString"),
     read
    ]
    object msgStr;
};

/////////////////////////////////////////////////////////////////////////////
//
//  System.Data.SNI.1

[
 dynamic: ToInstance,
 Description("System.Data.SNI.1"),
 Guid("{C9996FA5-C06F-F20C-8A20-69B3BA392315}"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_SNI_1 : EventTrace
{
};

[
 dynamic: ToInstance,
 Description("System.Data.SNI.1"),
 Guid("{C9996FA6-C06F-F20C-8A20-69B3BA392315}"),
 DisplayName("System.Data.SNI"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_SNI_1_Trace : Bid2Etw_System_Data_SNI_1
{
};

[
 dynamic: ToInstance,
 Description("System.Data.SNI.1 formatted output (A)"),
 EventType(17),
 EventTypeName("TextA"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_SNI_1_Trace_TextA : Bid2Etw_System_Data_SNI_1_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringA"),
     extension("RString"),
     read
    ]
    object msgStr;
};

[
 dynamic: ToInstance,
 Description("System.Data.SNI.1 formatted output (W)"),
 EventType(18),
 EventTypeName("TextW"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_SNI_1_Trace_TextW : Bid2Etw_System_Data_SNI_1_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringW"),
     extension("RWString"),
     read
    ]
    object msgStr;
};

/////////////////////////////////////////////////////////////////////////////
//
//  System.Data.OracleClient.1

[
 dynamic: ToInstance,
 Description("System.Data.OracleClient.1"),
 Guid("{DCD90923-4953-20C2-8708-01976FB15287}"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_OracleClient_1 : EventTrace
{
};

[
 dynamic: ToInstance,
 Description("System.Data.OracleClient.1"),
 Guid("{DCD90924-4953-20C2-8708-01976FB15287}"),
 DisplayName("System.Data.OracleClient"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_OracleClient_1_Trace : Bid2Etw_System_Data_OracleClient_1
{
};

[
 dynamic: ToInstance,
 Description("System.Data.OracleClient.1 formatted output (A)"),
 EventType(17),
 EventTypeName("TextA"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_OracleClient_1_Trace_TextA : Bid2Etw_System_Data_OracleClient_1_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringA"),
     extension("RString"),
     read
    ]
    object msgStr;
};

[
 dynamic: ToInstance,
 Description("System.Data.OracleClient.1 formatted output (W)"),
 EventType(18),
 EventTypeName("TextW"),
 locale("MS\\0x409")
]
class Bid2Etw_System_Data_OracleClient_1_Trace_TextW : Bid2Etw_System_Data_OracleClient_1_Trace
{
    [
     WmiDataId(1),
     Description("Module ID"),
     read
    ]
    uint32 ModID;

    [
     WmiDataId(2),
     Description("Text StringW"),
     extension("RWString"),
     read
    ]
    object msgStr;
};
